### PR TITLE
Added Login and Register page

### LINKED ISSUE #1: feat: add login and registration Page
## Expected Behavior

- [ ] UI for Sign In
- [ ] UI for Sign Up

### PR DESCRIPTION
**Pull request by pavithra-064**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bug Fix
- [x] New Feature
- [x] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe below:
   I have added login and register page for the bookstore website . I have also added a book icon for the website.
**Checklist**
- [x] I have read the **[CONTRIBUTING Guidelines](https://github.com/AOSP-NIT-Surat/Bookstore-Frontend-web/blob/main/.github/CONTRIBUTING.md)**.
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

**Any Other information:**
I am a novice front end web developer and this is my first time participating in open source contribution. Thank you for assigning me and please accept my pull request.

### CODE REVIEW

**Comment by GrayFlash** [comment]
@pavithra-064 add a Image in comments about the resulting output, also delete the package-lock.json file from the PR, and add its name to .gitignore file.

**Comment by pavithra-064** [comment]
Should i also remove the navbar?

**Comment by astonizer** [comment]
@pavithra-064 yes, remove the navbar as it's a different issue. You have put the new files in the root directory but try to follow proper directory structure. If you're creating an entirely new page, put the relevant files under `/pages` directory and if just small components that go inside a page, then put such files under `/components` directory.

**Comment by pavithra-064** [comment]
so all the changes must be under pages/component directory,right?

**Comment by astonizer** [comment]
@pavithra-064 keep the login.js and register.js files under `/pages` directory. The design also needs to be improved, try to keep some uniformity in spacing between the form elements.

**Comment by pavithra-064** [comment]
Screenshot (430)
Screenshot (429)

is this ok? I have moved login and register page under pages directory and also removed package-lock.json and can I give the pull request now?

**Comment by madrix01** [comment]
i think in signup page , this is no spacing in top and bottom, can you try to make it like the login page ?

**Comment by madrix01** [comment]
@pavithra-064  an always make a new branch from `main` for solving different issues. never edit code on main branch.

**Comment by pavithra-064** [comment]
> i think in signup page , this is no spacing in top and bottom, can you try to make it like the login page ?

okey i will do it

**Comment by pavithra-064** [comment]
> @pavithra-064 an always make a new branch from `main` for solving different issues. never edit code on main branch.

Sorry for that and will implement from next change onwards.

**Pull request merged**
