### PR TITLE
added navigation bar

### LINKED ISSUE #2: feat: add navigation bar
- [ ] Design and add a basic navbar which should contain the following:
- Logo (Original image or plain text for the time being) which should redirect to home page `/`.
- Navbar links for register `/register` and login `/login`.
<br/>

- [ ] Navbar should be responsive, to support small screens.
- The links should get replaced with a Hamburger button(or any relevant).
- It should display the links in a list, when clicked.

### PR DESCRIPTION
**Pull request by SGR007**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bug Fix
- [x] New Feature
- [x] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe below:

**Checklist**
- [x] I have read the **[CONTRIBUTING Guidelines](https://github.com/AOSP-NIT-Surat/Bookstore-Frontend-web/blob/main/.github/CONTRIBUTING.md)**.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)

**Any Other information:**

### CODE REVIEW

**Review by astonizer — CHANGES_REQUESTED** [review]
Looks good but keep some margin between the nav links & logo, and the corners. Try to centralize the navbar content.

**Comment by SGR007** [comment]
> Looks good but keep some margin between the nav links & logo, and the corners. Try to centralize the navbar content.

ok, will do the changes

**Comment by SGR007** [comment]
Screenshot 2021-10-03 193121

Screenshot 2021-10-03 193156

Does this looks good, added some margin

**Comment by SGR007** [comment]
Screenshot 2021-10-03 203205

done some improvement, made register and login link to be appear as button and increased logo size

**Review by astonizer — APPROVED** [review]

**Pull request merged**
